name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Verify JSON Syntax
      run: |
        sudo apt-get -qq install yajl-tools >/dev/null
        ./verify.py
